# Generated by Django 5.1.6 on 2025-03-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObesityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('family_history', models.BooleanField()),
                ('favc', models.BooleanField()),
                ('fcvc', models.FloatField()),
                ('ncp', models.IntegerField()),
                ('caec', models.CharField(max_length=20)),
                ('smoke', models.BooleanField()),
                ('ch2o', models.FloatField()),
                ('scc', models.BooleanField()),
                ('faf', models.FloatField()),
                ('tue', models.FloatField()),
                ('calc', models.CharField(max_length=20)),
                ('mtrans', models.CharField(max_length=20)),
                ('obesity_level', models.CharField(max_length=50)),
            ],
        ),
    ]
