# Generated by Django 5.1.6 on 2025-03-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_regression', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obesitydata',
            name='caec',
        ),
        migrations.RemoveField(
            model_name='obesitydata',
            name='calc',
        ),
        migrations.RemoveField(
            model_name='obesitydata',
            name='ch2o',
        ),
        migrations.RemoveField(
            model_name='obesitydata',
            name='faf',
        ),
        migrations.RemoveField(
            model_name='obesitydata',
            name='family_history',
        ),
        migrations.RemoveField(
            model_name='obesitydata',
            name='fcvc',
        ),
        migrations.RemoveField(
            model_name='obesitydata',
            name='mtrans',
        ),
        migrations.RemoveField(
            model_name='obesitydata',
            name='ncp',
        ),
        migrations.RemoveField(
            model_name='obesitydata',
            name='scc',
        ),
        migrations.RemoveField(
            model_name='obesitydata',
            name='tue',
        ),
    ]
